<?php
	$themeCfg = Mage::helper('mosera/data');
	$partnersStyle = '';
	$bgColor = $themeCfg->getField('ourpartners_bg_color');
	$bgImg = Mage::helper('cms')->getBlockTemplateProcessor()->filter($themeCfg->getField('ourpartners_bg_img'));

	if (preg_match('/^wysiwyg/i', $bgImg)) {
		$bgImg = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$bgImg;
		$partnersStyle .= 'background-image: url(\''.$bgImg.'\');';
	}

	$partnersStyle .= ($bgColor) ? 'background-color: '.$bgColor.';' : '';

	$enabled = $themeCfg->getField('ourpartners_enabled');
	if($enabled == 1) :
		$partners = $themeCfg->getField('ourpartners_partners');
		$array_partners = unserialize($partners);
		$id = 1;
		$collect_partners = array();
		foreach($array_partners as $key=>$partner){
			$partner['id'] = $id;
			$partner['image'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($partner['image']);
			if (preg_match('/^wysiwyg/i', $partner['image'])) {
				$partner['image'] = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$partner['image'];
			}
			$partner['link'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($partner['link']);
			$haveHttp =  strpos(trim($partner['link']), "http://"); 
			if(!$haveHttp && ($haveHttp!==0)){
				//$partner['link'] = "http://" . trim($partner['link']);  
			}else {
				//$partner['link'] = trim($partner['link']);
			}
			
			
			$partner['title'] = $partner['title'];
			$collect_partners[] = $partner;
			$id++;
		}
if($collect_partners) :
	$blockId ='sns_partner_'.rand().time();
?>
<div id="sns_partners" class="wrap" >
	<div class="sns_module">
		<div class="sns_partner block sns-slider" id="<?php echo $blockId; ?>">
			<div class="block-title">
				<div class="title"><span><?php echo $this->__($themeCfg->getField('ourpartners_title')); ?></span></div>
				<div class="navslider">
				<a class="prev" href="#"><i class="fa fa-caret-left"></i></a>
				<a class="next" href="#"><i class="fa fa-caret-right"></i></a>
			</div>
			</div>
			<div class="partners_slider slider-wrap">
				<div class="partners_slider_in">
					<div class="our_partners" >
						<?php foreach($collect_partners as $partner) : ?>
							<div class="wrap">
								<div class="wrap_in">
									<a target="<?php echo $partner['target']; ?>" href="<?php echo $partner['link']; ?>">
										<img alt="" src="<?php echo $partner['image']; ?>" />
									</a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
			<script>
				jQuery(document).ready(function($) {
						$('#<?php echo $blockId; ?> .our_partners').owlCarousel({
							items: 6,
				            responsive : {
										    0 : { items: 2},
										    480 : { items: 3 },
										    768 : { items: 4 },
										    992 : { items: 6 }
										},
							loop:true,
						    autoplay:true,
						    dots: false,
						    nav: false,
                        	navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
						    autoplayTimeout:5000,
						    autoplayHoverPause:true,
							slideSpeed :8000,
							onInitialized: callback
						});
					function callback(event) {
			   			if(this._items.length > this.options.items){
						        $('#<?php echo $blockId; ?> .navslider').show();
						    }else{
						        $('#<?php echo $blockId; ?> .navslider').hide();
						    }
					}
					$('#<?php echo $blockId; ?> .navslider .prev').on('click', function(e){
						e.preventDefault();
						$('#<?php echo $blockId; ?> .our_partners').trigger('prev.owl.carousel');
					});
					$('#<?php echo $blockId; ?> .navslider .next').on('click', function(e){
						e.preventDefault();
						$('#<?php echo $blockId; ?> .our_partners').trigger('next.owl.carousel');
					});
				});
			</script>
		</div>
	</div>
</div>
<?php endif; ?>
<?php endif; ?>