<?php
	$themeCfg = Mage::helper('mosera/data');
	$enabled = $themeCfg->getField('slideshow_enabled');
	$timeAuto = $themeCfg->getField('slideshow_autoplay');
	$animateIn = $themeCfg->getField('slideshow_animatein');
	$animateOut = $themeCfg->getField('slideshow_animateout');
	$width = $themeCfg->getField('slideshow_width');
	$height = $themeCfg->getField('slideshow_height');
	if(!file_exists(Mage::getBaseDir('media') . '/wysiwyg/'.$width.'x'.$height.'.png')) {
        $imageBg = imagecreate($width, $height);
        $white = imagecolorallocate($imageBg, 255, 255, 255);
		imagecolortransparent($imageBg, $white);
        imagepng($imageBg, Mage::getBaseDir('media') . '/wysiwyg/'.$width.'x'.$height.'.png');
        imagedestroy($imageBg);
    }
    $bg = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/wysiwyg/'.$width.'x'.$height.'.png';
    // echo $bg;die;
	if($enabled == 1) :
		$images = $themeCfg->getField('slideshow_images');
		$array_images = unserialize($images);
		$id = 1;
		$collect_images = array();
		foreach($array_images as $key=>$image){
			$image['id'] = $id;
			$image['image'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($image['image']);
			$image['type'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($image['type']);
			if (preg_match('/^wysiwyg/i', $image['image'])) {
				$image['image'] = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$image['image'];
			}
			$image['link'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($image['link']);
			$haveHttp =  strpos(trim($image['link']), "http://"); 
			if(!$haveHttp && ($haveHttp!==0)){
				//$image['link'] = "http://" . trim($image['link']);  
			}else {
				//$image['link'] = trim($image['link']);
			}
			$image['title'] = $image['title'];
			$collect_images[] = $image;
			$id++;
		}
if($collect_images) :
	$blockId ='sns_slideshow_'.rand().time();
?>
<div id="sns_slideshow_wrapper" class="wrap">
		<div class="sns_slideshow" id="<?php echo $blockId; ?>">

			<div class="slider_images">
				<?php foreach($collect_images as $image) : ?>
					 <div class="item<?php if($image['type'] == 2){echo('-video');}  ?>" style="<?php if($image['type'] == 2){echo('height:'.$height.'px;');}  ?>text-align: center; background: url(<?php echo $image['image']; ?>) repeat scroll center center / cover  rgba(0, 0, 0, 0)">
						<a title="<?php echo $image['title']; ?>" href="<?php echo $image['link']; ?>" class="<?php if($image['type'] == 2){echo('owl-video');}else{echo('slideimg');}  ?>">

							<img alt="<?php echo $image['title']; ?>" src="<?php echo $bg; ?>" />
						</a>
					</div> 

				<?php endforeach; ?>
				<!-- <div class="item-video" style="height: 806px;" data-merge="3"><a class="owl-video" href="http://vimeo.com/23924346"></a></div> -->
			</div>
			<div class="container">
				<div class="navslider">
					<a class="next" href="#">Next</a>
					<a class="prev" href="#">Prev</a>
				</div>
			</div>
			<script>
				jQuery(document).ready(function($) {
					var owl = jQuery('#<?php echo $blockId; ?> .slider_images');
					var owl_options = {
						items:1,
					    margin:0,
					    loop:true,
					    responsiveClass:true,
					    responsiveBaseElement: ".sns_slideshow",
					    nav: true,
					    // navText: ["<span><i class='fa fa-long-arrow-left'></i> Prev</span>","<span><i class='fa fa-long-arrow-right'></i>Next</span>"],
					    dots: true,
					    video:true,
					    stagePadding:0,
					    smartSpeed:450,
					    animateOut: '<?php echo $animateOut ?>',
					    animateIn: '<?php echo $animateIn ?>',
					    autoplay: true,
					    autoplayTimeout: <?php echo $timeAuto ?>,
					    autoplayHoverPause: true,
						// onInitialized: callback,
						// onInitialized: onRefreshed
						onRefreshed: function() {
							var height_slideshow = $('#<?php echo $blockId; ?> .slider_images .slideimg img').outerHeight();
							$("#<?php echo $blockId; ?> .item-video").css("height", height_slideshow);
						}
						
					};
					owl.owlCarousel(owl_options);
					function callback(event) {
			   			if(this._items.length > this.options.items){
						        jQuery('#<?php echo $blockId; ?> .navslider').show();
						    }else{
						        jQuery('#<?php echo $blockId; ?> .navslider').hide();
						    }
					}
					// function onRefreshed(event) {
			  //  			var height_slideshow = $('#<?php echo $blockId; ?> .slider_images .item > a ').outerHeight();
		   //                  $("#<?php echo $blockId; ?> .item-video").css("height", height_slideshow);
					// }
					jQuery('#<?php echo $blockId; ?> .navslider .prev').on('click', function(e){
						e.preventDefault();
						jQuery('#<?php echo $blockId; ?> .slider_images').trigger('prev.owl.carousel');
					});
					jQuery('#<?php echo $blockId; ?> .navslider .next').on('click', function(e){
						e.preventDefault();
						jQuery('#<?php echo $blockId; ?> .slider_images').trigger('next.owl.carousel');
					});

					jQuery('[name="sns_cfg_general_layoutType"]').on('change', function(){
						// destroy carousel
						owl.trigger('destroy.owl.carousel').removeClass('owl-carousel owl-loaded');
						owl.find('.owl-stage-outer').children().unwrap();
						// reinitialize carousel
						owl.owlCarousel(owl_options);
					});
				});

				

			</script>
		</div>
</div>
<?php endif; ?>
<?php endif; ?>