<?php if (Mage::getStoreConfig(AW_Blog_Helper_Config::XML_TAGCLOUD_SIZE) && $this->getCollection()->count()): ?>
    <div class="menu-tags">
		<div class="block-title">
            <i class="fa fa-tags"></i>
		<span><?php echo Mage::helper('blog')->__('Tags'); ?></span>
		</div>
        <ul class="tagcloud">
            <?php foreach ($this->getCollection() as $tag): ?>
                <li><a class="tag-count-<?php echo $this->getTagWeight($tag) ?>" href="<?php echo $this->getTagHref($tag) ?>"><?php echo $tag->getTag() ?></a></li>
		   <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
