<?php
/*------------------------------------------------------------------------
 # SNS Products - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$themeCfg =   Mage::helper('mosera/data');
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}
$uniqued = rand().time();

$imgSizeS = $themeCfg->getImgSize('S');
$imgSize = $themeCfg->getImgSize('XL');
$imgWidth = $imgSize[0];
$imgHeight = $imgSize[1];

?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="sns_lider<?php echo $uniqued; ?>" class="block sns-slider">
	<div class="slider-inner">
    	<div class="block-title">
    		<?php if($this->title!="") : ?>
    			<strong><?php echo $this->__($this->title);?></strong>
			<?php endif; ?>
    		<?php if($this->pretext!="") : ?>
    			<p class="pretext"><?php echo $this->__($this->pretext);?></p>
			<?php endif; ?>
			<div class="navslider">
				<a class="prev" href="#"><i class="fa fa-caret-left"></i></a>
				<a class="next" href="#"><i class="fa fa-caret-right"></i></a>
			</div>
    	</div>
		<div class="container-slider">
			<div class="products-grid">
			    <?php $i=0; foreach($_productCollection as $_product) : ?>
			    	<?php
				        $saleLabel = false;
				        $newLabel = false;
						$now = date("Y-m-d");
				        $newsFrom= substr($_product->getData('news_from_date'),0,10);
				        $newsTo=  substr($_product->getData('news_to_date'),0,10);
				        $price = $_product->getPrice();
				        $finalPrice = $_product->getFinalPrice();
				        if(!$newsTo && $newsFrom && $now>=$newsFrom) $newLabel = true;
				        if($newsTo && !$newsFrom && $now<=$newsTo) $newLabel = true;
						if ($now>=$newsFrom && $now<=$newsTo && $themeCfg->getField('general_useTagNew')){ 
							$newLabel = true;
						}
						if(isset($price) && isset($finalPrice) && $finalPrice < $price && $themeCfg->getField('general_useTagSale')) $saleLabel = true;
						$endTime = Mage::getModel('core/date')->date("Y, m, d, H, i, s", $_product->getSpecialToDate());
                        $nowTime = Mage::getModel('core/date')->date("Y, m, d, H, i, s", Mage::getModel('core/date')->timestamp(time()));
                        $haveAdditional = 0;
						if(count(Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages()) > 0 && $themeCfg->getField('general_useImageHover')==1){
							 $haveAdditional = 1;
						}

					?>
                    
			        <div class="item">
						<div class="item-inner">
							<div class="prd">
								<div class="item-img<?php echo $class; ?> clearfix<?php echo ($haveAdditional == 1)?' have-additional':'';?>" >
	                                <div class="ico-label">
	                                    <?php if ($newLabel) echo "<span class='ico-product ico-new'>".$this->__('New')."</span>"; ?>
	                                    <?php if ($saleLabel) echo "<span class='ico-product ico-sale'>".$this->__('Sale')."</span>"; ?>
	                                    
	                                </div> 
									<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
				                	  <span class="img-main">
										<img 
											data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" 
											src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgSize[0], $imgSize[1]); ?>" 
											alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</span>
										<?php
										if($haveAdditional == 1){
										$_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
										$i_im = 0;
										foreach ($_gallery as $_image ):
										$i_im++;
										
										if($i_im == 2){  ?>
										<span class="img-additional">
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $_image->getFile())->resize($imgSize[0], $imgSize[1]); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
										</span>
										<?php
										break;
										}
										endforeach;
										} ?>
				                </a>

								    
									<?php if ($saleLabel && $_product->getSpecialToDate() && $nowTime < $endTime && $themeCfg->getField('general_dealsCountdown')): ?>
										<div class="countdown" data-endtime="<?php echo $endTime; ?>"></div>
									<?php endif; ?>

									<div class="action-bot">
				                        <div class="actions">
				                            <ul class="add-to-links">
				                            	
				                                <li class="link-addtocart">
				                                	<div class="wrap-addtocart">
									                    <?php if($_product->isSaleable()): ?>
									                        <button title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->__('Add to cart') ?>" >
									                        	<i class="fa fa-shopping-cart"></i>
									                        	<strong><?php echo $this->__('Add to cart') ?></strong>
									                        </button>
									                    <?php else: ?>
									                        <span class="btn-cart out-of-stock" title="<?php echo $this->__('Out of stock') ?>" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->__('Out of stock') ?>">
									                        	<span><?php echo $this->__('Out of stock') ?></span></span>
									                    <?php endif; ?>
									            	</div>
				                                </li>
				                                <li data-id="qv_item_<?php echo $_product->getId(); ?>" class="wrap-quickview">
				                                    <div class="quickview-wrap">
				                                        <a class="sns-btn-quickview"  href="<?php echo $_product->getProductUrl() ?>" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->__('Quickview') ?>">
				                                            <i class="fa fa-eye"></i>
				                                        </a>
				                                    </div>
				                                </li>
				                            </ul>
				                        </div>
						            </div>
								</div>
								<div class="item-info">
					                <div class="info-inner">
					                    <div class="item-title">
								            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
								                <?php
								                    echo Mage::helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getName(), 'name'), 22);
								                ?>
								            </a>
								        </div>
				                        <div class="item-price">
				                        	<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
				                            <?php echo $this->getPriceHtml($_product, false, $uniqued) ?>
				                            
				                        </div>
				                        <a class="tab-redmore" href="<?php echo $item->link ?>" onclick="javascript: return true"  title="<?php echo $item->title?>" >
												Learn more
											</a>
					                </div>
				            	</div>
							</div>
						</div>
			        </div>
                    
			    <?php endforeach; ?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $('#sns_lider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
        	items: 4,
            responsive : {
			    0 : { items: 1 },
			    480 : { items: 2 },
			    768 : { items: 2 },
			    992 : { items: 3 },
			    1200 : { items: 4 }
			},
			loop:true,
		    responsiveClass:true,
		    nav: false,
		    navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
		    dots: true,
            slideSpeed : 800,
            autoHeight : true,
            addClassActive: true,
            onInitialized: callback
        });
		function callback(event) {
			
   			if(this._items.length > this.options.items){
			        $('#sns_lider<?php echo $uniqued; ?> .navslider').show();
			    }else{
			        $('#sns_lider<?php echo $uniqued; ?> .navslider').hide();
			    }
		}
		$('#sns_lider<?php echo $uniqued; ?> .navslider .prev').on('click', function(e){
			e.preventDefault();
			$('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('prev.owl.carousel');
		});
		$('#sns_lider<?php echo $uniqued; ?> .navslider .next').on('click', function(e){
			e.preventDefault();
			$('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('next.owl.carousel');
		});
    });
//]]>
</script>

<?php endif; ?>

