<?php
/*------------------------------------------------------------------------
 # SNS Products - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$themeCfg =   Mage::helper('mosera/data');
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}
$uniqued = rand().time();

$imgSizeS = $themeCfg->getImgSize('L');
$imgSize = $themeCfg->getImgSize('XL');
$imgSize[0] = 83;
$imgSize[1] = 92;

?>
<?php if(!count($_productCollection)) : ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="sns_lider<?php echo $uniqued; ?>" class="block sns-slider stylev3">
	<div class="slider-inner">
    	<div class="block-title">
    		<?php if($this->title!="") : ?>
    			<strong><?php echo $this->__($this->title);?></strong>
			<?php endif; ?>
    		<?php if($this->pretext!="") : ?>
    			<p class="pretext"><?php echo $this->__($this->pretext);?></p>
			<?php endif; ?>
			<div class="navslider">
				<a class="prev" href="#"><i data-icon="4" aria-hidden="true" class="fs1 fa"></i></a>
				<a class="next" href="#"><i data-icon="5" aria-hidden="true" class="fs1 fa"></i></a>
			</div>
    	</div>
		<div class="container-slider">
			<div class="products-grid">
			    <?php $i=0; foreach($_productCollection as $_product) : ?>
			    	<?php
				        $saleLabel = false;
				        $newLabel = false;
						$now = date("Y-m-d");
				        $newsFrom= substr($_product->getData('news_from_date'),0,10);
				        $newsTo=  substr($_product->getData('news_to_date'),0,10);
				        $price = $_product->getPrice();
				        $finalPrice = $_product->getFinalPrice();
				        if(!$newsTo && $newsFrom && $now>=$newsFrom) $newLabel = true;
				        if($newsTo && !$newsFrom && $now<=$newsTo) $newLabel = true;
						if ($now>=$newsFrom && $now<=$newsTo && $themeCfg->getField('general_useTagNew')){ 
							$newLabel = true;
						}
						if(isset($price) && isset($finalPrice) && $finalPrice < $price && $themeCfg->getField('general_useTagSale')) $saleLabel = true;
						$endTime = Mage::getModel('core/date')->date("Y, m, d, H, i, s", $_product->getSpecialToDate());
                        $nowTime = Mage::getModel('core/date')->date("Y, m, d, H, i, s", Mage::getModel('core/date')->timestamp(time()));

					?>
                    <?php if($i%3 == 0) {
                        echo '<div class="row-item">';
                    }
                    ?>
			        <div class="item">
						<div class="item-inner">
							<div class="prd">
							<div class="item-img clearfix">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image<?php echo (count(Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages()) > 0)?' have-additional':'';?>">
									<span class="img-main">
									<img 
										data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" 
										src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgSize[0], $imgSize[1]); ?>" 
										alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									</span>
								</a>

							    
								<?php if ($saleLabel && $_product->getSpecialToDate() && $nowTime < $endTime && $themeCfg->getField('general_dealsCountdown')): ?>
									<div class="countdown" data-endtime="<?php echo $endTime; ?>"></div>
								<?php endif; ?>
								</div>
								<div class="item-info">
								    <div class="info-inner">
								        <div class="item-title">
								            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
								                <?php
								                    echo Mage::helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getName(), 'name'), 22);
								                ?>
								            </a>
								        </div>
								        
								        <div class="rating">
								        	<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
								        </div>
								        <div class="item-price">
								            <?php echo $this->getPriceHtml($_product, false, rand().time()) ?>     
								        </div>
								    </div>
								</div>
							</div>
						</div>
			        </div>
                    <?php
                    $i++;
                    if($i%3 == 0 || $i == count($_productCollection)) {
                        echo '</div>'; // endrow
                    }
                    ?>
			    <?php endforeach; ?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $('#sns_lider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
        	items: 4,
            responsive : {
			    0 : { items: 1 },
			    480 : { items: 2 },
			    768 : { items: 2 }
			},
			loop:false,
		    responsiveClass:true,
		    nav: false,
		    autoHeight: true,
		    autoplay: false,
            addClassActive: true,
            onInitialized: callback
        });
		function callback(event) {
			
   			if(this._items.length > this.options.items){
			        $('#sns_lider<?php echo $uniqued; ?> .navslider').show();
			    }else{
			        $('#sns_lider<?php echo $uniqued; ?> .navslider').hide();
			    }
		}
		$('#sns_lider<?php echo $uniqued; ?> .navslider .prev').on('click', function(e){
			e.preventDefault();
			$('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('prev.owl.carousel');
		});
		$('#sns_lider<?php echo $uniqued; ?> .navslider .next').on('click', function(e){
			e.preventDefault();
			$('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('next.owl.carousel');
		});
    });
//]]>
</script>

<?php endif; ?>